apiVersion: secrets.keysmith.io/v1alpha1
kind: RotationRecord
metadata:
  labels:
    app.kubernetes.io/name: keysmith
    app.kubernetes.io/managed-by: kustomize
  name: rotationrecord-sample
spec:
  # TODO(user): Add fields here
